services:
  app:
    build:  .
    ports:
      - "9136:9136"
    environment:
      - SPRING_MAIL_HOST
      - SPRING_MAIL_PASSWORD
      - SPRING_MAIL_PORT
      - SPRING_MAIL_USERNAME
      - SPRING_DATASOURCE_PASSWORD
      - SPRING_DATASOURCE_USERNAME
      - SPRING_DATASOURCE_URL
    depends_on:
      - db
  db:
    image: mysql:8.3
    container_name: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=nkjweb
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
    ports:
      - "8800:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: